import { writeFileSync } from 'fs';

const data = [
  {
    id: 'sof-001',
    title_original: '\u99ac\u862d\u59d1\u5a18',
    title_romanized: null,
    title_chinese: '\u99ac\u862d\u59d1\u5a18',
    artist: '\u76e7\u975c\u5b50 (Lu Jingzi)',
    language_claimed: 'Amis',
    language_evidence: 'Song originates from the Malan Amis community (Falangaw, Taitung). Lu Jingzi is a known Amis performer. Oral tradition roots documented within the Amis community.',
    ethnic_group_claimed: 'Amis (Pangcah)',
    ethnic_group_evidence: 'Linked to Malan Tribe (Falangaw), Taitung. Reflects Amis matrilineal social dynamics and autonomy.',
    performers: [{ id: 'perf-001', name_display: '\u76e7\u975c\u5b50 (Lu Jingzi)', names_zh: ['\u76e7\u975c\u5b50'], names_rom: ['Lu Jingzi', 'Ceko'], role: ['vocalist'], ethnic_group: 'Amis (Pangcah)' }],
    source_platform: 'YouTube',
    url: 'https://www.youtube.com/watch?v=FbBKtaoMG-I',
    youtube_url: 'https://www.youtube.com/watch?v=FbBKtaoMG-I',
    lyrics_url: null,
    album_or_source: 'Traditional / Various recordings',
    year: '1969',
    location_claimed: 'Malan Tribe (Falangaw), Taitung',
    region: 'Taitung',
    genre: 'Modern Folk',
    tags: ['amis', 'folk', 'traditional', 'malan', 'matrilineal'],
    source_snippets: 'Alternate titles: \u99ac\u862d\u5c71\u6b4c, \u5c71\u5730\u60c5\u6b4c, \u96e2\u5225\u6545\u9109. Earliest known recording by Lin Ba-zhong & Chen Yue-he (1961). Mandarin adaptation by Mei Dai popularized melody. Difang Duana & Malan Singers on Circle of Life (1998).',
    verification_notes: 'Multiple performers and eras; Lu Jingzi 1969 is the reference Amis version. As a protected cultural expression, care should be taken to distinguish from the Elders\u2019 Drinking Song.',
    confidence: 'medium',
    verification_status: 'candidate',
    needs_manual_verification: true,
    checked_by_me: false,
    date_added: '2026-05-14',
    lyrics: {
      song_id: 'sof-001',
      lyrics_original: null,
      lyrics_romanized: "Inaaw, hay ya amaaw!\nSololen kako, ina!\nMatini similicayay ko wawa no tao to tireng ako, ina.\nAno caay kamo pisolol to tireng ako, ina.\nO maan ko pinang to nikapatay?\nMakinotolo, toloan no kasolin.",
      lyrics_translation_zh: '\u5abd\u5abd\u554a\uff0c\u7238\u7238\u554a\uff01\n\u8acb\u7b54\u61c9\u6211\u5427\uff0c\u5abd\u5abd\uff01\n\u73fe\u5728\u6709\u5225\u4eba\u5bb6\u7684\u5b69\u5b50\u4f86\u5411\u6211\u63d0\u89aa\u4e86\u3002\n\u5982\u679c\u9019\u6bb5\u59fb\u7de3\u4f60\u5011\u4e0d\u51c6\u8a31\uff0c\u5abd\u5abd\u3002\n\u6211\u4e0d\u77e5\u9053\u6703\u767c\u751f\u4ec0\u9ebc\u5f8c\u679c\uff1f\n\u6211\u5c07\u8eba\u5728\u9435\u8ecc\u4e0a\uff0c\u8b93\u706b\u8eca\u5c07\u6211\u622a\u6210\u4e09\u6bb5\u3002',
      lyrics_translation_en: null,
      lyrics_source: 'Community transcription; unattributed web source.',
      lyrics_rights_status: 'unverified_transcription',
      lyrics_notes: '[TESTING] show_publicly enabled for UI dev. Rights unclear \u2014 disable before production.',
      has_permission: false,
      show_publicly: true
    }
  },
  {
    id: 'sof-002',
    title_original: 'Kulumaha',
    title_romanized: 'Kulumaha',
    title_chinese: '\u56de\u5bb6\u5427',
    artist: '\u91d1\u570b\u5bf6 (Jin Guobao)',
    language_claimed: 'Bunun',
    language_evidence: 'Composed by Jin Guobao, a Bunun pastor. Song identified as Bunun indigenous gospel folk.',
    ethnic_group_claimed: 'Bunun',
    ethnic_group_evidence: 'Composer Jin Guobao is Bunun. Featured in film \u807d\u898b\u6b4c\u518d\u5531 (Listen Before You Sing) by Vox Nativa Taiwan (\u539f\u8072\u7ae5\u8072\u5408\u5531\u5718).',
    performers: [
      { id: 'perf-002', name_display: '\u91d1\u570b\u5bf6 (Jin Guobao)', names_zh: ['\u91d1\u570b\u5bf6'], names_rom: ['Jin Guobao'], role: ['composer'], ethnic_group: 'Bunun', notes: 'Deceased Bunun pastor, composer of Kulumaha' },
      { id: 'perf-003', name_display: '\u539f\u8072\u7ae5\u8072\u5408\u5531\u5718 (Vox Nativa Taiwan)', names_zh: ['\u539f\u8072\u7ae5\u8072\u5408\u5531\u5718'], names_rom: ['Vox Nativa Taiwan'], role: ['group', 'vocalist'], ethnic_group: 'Bunun', notes: "Indigenous children's choir featured in Listen Before You Sing film" }
    ],
    source_platform: 'YouTube',
    url: 'https://www.youtube.com/watch?v=QtglFSVOURM',
    youtube_url: 'https://www.youtube.com/watch?v=QtglFSVOURM',
    lyrics_url: null,
    album_or_source: 'Original composition; various choral covers',
    year: null,
    location_claimed: null,
    region: null,
    genre: 'Indigenous Gospel / Folk',
    tags: ['bunun', 'gospel', 'folk', 'spiritual', 'film'],
    source_snippets: 'Covered by \u99ac\u8a60\u6069 (Ma Yongen) in indigenous fusion style. Two non-Formosan songs with the same Chinese title excluded.',
    verification_notes: 'Disambiguation needed: only this Bunun gospel song is Formosan-relevant. Mandopop and Chinese drama versions excluded.',
    confidence: 'medium',
    verification_status: 'candidate',
    needs_manual_verification: true,
    checked_by_me: false,
    date_added: '2026-05-14',
    lyrics: {
      song_id: 'sof-002',
      lyrics_original: null,
      lyrics_romanized: 'I sia madumduman tu dan\nUka na mahtu sinadan\nNi tu haiap tu na masikua\nKaivakaiva Saikin Sain Cin\nMinbuhbuh Sia Madumduman\nMahanimulmul Inak is-ang\nKulumaha kulumah\nKulumaha Kulumaha laupa ku\nSida nga mas\nSabinaz\nPasasinhal imitatu lahaiban',
      lyrics_translation_zh: '\u8d70\u5728\u9ed1\u6697\u7684\u9053\u8def\u4e0a\n\u7121\u4eba\u53ef\u4ee5\u501a\u9760\n\u4e0d\u77e5\u9053\u6211\u8a72\u600e\u9ebc\u8fa6\n\u6211\u7684\u5fc3\u5728\u9019\u5730\u65b9\u614c\u5f35\u5fac\u5fa8\n\u5728\u9019\u9ed1\u6697\u4e2d\u5931\u843d\n\u6211\u7684\u5fc3\u5f88\u5bc2\u5bde\u5f88\u7121\u52a9\n\u56de\u5bb6\u5427\uff0c\u56de\u5bb6\n\u56de\u5bb6\u5427\uff0c\u56de\u5bb6\uff0c\u5c31\u662f\u73fe\u5728\n\u6211\u4f9d\u9760\u7962\n\u6211\u7684\u4e3b\u8036\u7a4c\n\u8acb\u7962\u7167\u4eae\u6211\u524d\u9762\u8981\u8d70\u7684\u9053\u8def',
      lyrics_translation_en: null,
      lyrics_source: 'YouTube video description / community transcription.',
      lyrics_rights_status: 'unverified_transcription',
      lyrics_notes: '[TESTING] show_publicly enabled for UI dev. Jin Guobao (deceased); rights holder unknown.',
      has_permission: false,
      show_publicly: true
    }
  },
  {
    id: 'sof-003',
    title_original: 'Aka Pisawad',
    title_romanized: 'Aka Pisawad',
    title_chinese: '\u4e0d\u8981\u653e\u68c4',
    artist: '\u8212\u7c73\u6069 (Suming Rupi)',
    language_claimed: 'Amis',
    language_evidence: 'Composed and performed by Suming Rupi, an Amis musician from Taitung. Written in Amis for film Wawa No Cidal.',
    ethnic_group_claimed: 'Amis (Pangcah)',
    ethnic_group_evidence: "Suming Rupi is an established Amis artist. Film Wawa No Cidal (Children of the Sun) is explicitly about Amis children's choir.",
    performers: [{ id: 'perf-004', name_display: '\u8212\u7c73\u6069 (Suming Rupi)', names_zh: ['\u8212\u7c73\u6069', '\u8212\u7c73\u6069\u00b7\u9b6f\u78a7'], names_rom: ['Suming Rupi', 'Suming'], role: ['vocalist', 'composer', 'lyricist'], ethnic_group: 'Amis (Pangcah)', notes: 'Award-winning Amis musician; Golden Horse & Golden Melody winner' }],
    source_platform: 'YouTube',
    url: 'https://www.youtube.com/watch?v=gzuEvkk-eg8',
    youtube_url: 'https://www.youtube.com/watch?v=gzuEvkk-eg8',
    lyrics_url: null,
    album_or_source: 'Wawa No Cidal (Children of the Sun) Original Motion Picture Soundtrack',
    year: '2015',
    location_claimed: null,
    region: 'Taitung',
    genre: 'Contemporary Indigenous Folk-Pop',
    tags: ['amis', 'film-ost', 'folk-pop', 'golden-horse', 'golden-melody', 'suming'],
    source_snippets: 'Won Best Original Film Song (Golden Horse Awards 2015) and Song of the Year (Golden Melody Awards 2016). Also released in Mandarin version on the same OST.',
    verification_notes: 'Well-documented entry with strong award record. Two versions exist: Amis original and Mandarin.',
    confidence: 'high',
    verification_status: 'needs_review',
    needs_manual_verification: true,
    checked_by_me: false,
    date_added: '2026-05-14',
    lyrics: {
      song_id: 'sof-003',
      lyrics_original: null,
      lyrics_romanized: "ya tato'eman i,\nhakowa ko pitala iso.\nadada ko faloco,\nterep han hokiya mihai konini a dmak.\nano tala'ayaw,\nmafohat ko lalan a misi'ayaw.\nano tala'ayaw,\ntatiih to, fancal to, sahto nga'ayay.\naka sawaden ko tileng.\no olip caay ka miliyaw patatikol.",
      lyrics_translation_zh: '\u5929\u5c07\u6697\u4e86\uff0c\n\u4f60\u9084\u9858\u610f\u7b49\u5f85\u591a\u4e45\u3002\n\u5fc3\u53d7\u50b7\u4e86\uff0c\n\u4f60\u662f\u5426\u4e5f\u9ed8\u9ed8\u5730\u627f\u53d7\u9019\u4e00\u5207\u3002\n\u5982\u679c\u751f\u547d\u7e7c\u7e8c\u5411\u524d\uff0c\n\u7e3d\u80fd\u770b\u5230\u524d\u65b9\u7684\u8def\u6703\u958b\u3002\n\u5982\u679c\u751f\u547d\u7e7c\u7e8c\u5411\u524d\uff0c\n\u4e0d\u8ad6\u9047\u5230\u58de\u7684\u3001\u597d\u7684\uff0c\u90fd\u662f\u503c\u5f97\u7d93\u9a57\u7684\u3002\n\u4e0d\u8981\u653e\u68c4\u81ea\u5df1\u3002\n\u751f\u547d\u4e0d\u6703\u91cd\u4f86\u3002',
      lyrics_translation_en: null,
      lyrics_source: 'KKBOX official lyrics listing. Composed/performed by Suming Rupi (\u8212\u7c73\u6069).',
      lyrics_rights_status: 'public_transcription',
      lyrics_notes: '[TESTING] show_publicly enabled. KKBOX is most authoritative public source.',
      has_permission: false,
      show_publicly: true
    }
  },
  {
    id: 'sof-004',
    title_original: 'Sapah Utux',
    title_romanized: 'Sapah Utux',
    title_chinese: null,
    artist: 'Unknown / Traditional',
    language_claimed: 'Seediq',
    language_evidence: "Identified from a playlist labeled 'Seediq Traditional Songs'. No direct linguistic analysis available.",
    ethnic_group_claimed: 'Seediq',
    ethnic_group_evidence: 'Playlist context only. Artist identity unconfirmed.',
    performers: [],
    source_platform: 'YouTube',
    url: null,
    youtube_url: null,
    lyrics_url: null,
    album_or_source: null,
    year: null,
    location_claimed: 'Nantou / Hualien',
    region: 'Nantou',
    genre: 'Traditional',
    tags: ['seediq', 'traditional', 'unverified'],
    source_snippets: '[MOCK DATA \u2014 synthetic entry for UI testing]',
    verification_notes: 'Low confidence. Source is an uncurated YouTube playlist. Title and artist require independent verification.',
    confidence: 'low',
    verification_status: 'candidate',
    needs_manual_verification: true,
    checked_by_me: false,
    date_added: '2026-05-14'
  },
  {
    id: 'sof-005',
    title_original: 'Vusam a Djalan',
    title_romanized: 'Vusam a Djalan',
    title_chinese: '\u7a2e\u5b50\u4e4b\u8def',
    artist: '\u963f\u91cc\u8292 (Aliamang)',
    language_claimed: 'Paiwan',
    language_evidence: 'Artist Aliamang is a documented Paiwan singer from Pingtung. Title uses Paiwan vocabulary (vusam = seed).',
    ethnic_group_claimed: 'Paiwan',
    ethnic_group_evidence: 'Artist origin documented as Paiwan, Pingtung County.',
    performers: [],
    source_platform: 'YouTube',
    url: null,
    youtube_url: null,
    lyrics_url: null,
    album_or_source: null,
    year: '2018',
    location_claimed: 'Pingtung',
    region: 'Pingtung',
    genre: 'Contemporary Folk',
    tags: ['paiwan', 'folk', 'contemporary'],
    source_snippets: '[MOCK DATA \u2014 synthetic entry for UI testing. Lyrics below are placeholder text only.]',
    verification_notes: "Checked against artist discography. Paiwan language confirmed by vocalist's own liner notes.",
    confidence: 'medium',
    verification_status: 'checked',
    needs_manual_verification: false,
    checked_by_me: true,
    date_added: '2026-05-14',
    lyrics: {
      song_id: 'sof-005',
      lyrics_original: '[Sample original Paiwan lyric line 1]\n[Sample original Paiwan lyric line 2]\n[Sample original Paiwan lyric line 3]',
      lyrics_romanized: '[Sample romanization line 1]\n[Sample romanization line 2]\n[Sample romanization line 3]',
      lyrics_translation_zh: '[\u7bc4\u4f8b\u4e2d\u6587\u7ffb\u8b6f\u7b2c\u4e00\u884c]\n[\u7bc4\u4f8b\u4e2d\u6587\u7ffb\u8b6f\u7b2c\u4e8c\u884c]\n[\u7bc4\u4f8b\u4e2d\u6587\u7ffb\u8b6f\u7b2c\u4e09\u884c]',
      lyrics_translation_en: '[Sample English translation line 1]\n[Sample English translation line 2]\n[Sample English translation line 3]',
      lyrics_source: 'Artist liner notes (mock)',
      lyrics_rights_status: 'artist_permission',
      lyrics_notes: 'Placeholder lyrics for UI testing only.',
      has_permission: true,
      show_publicly: true
    }
  },
  {
    id: 'sof-006',
    title_original: 'Mivanwa',
    title_romanized: 'Mivanwa',
    title_chinese: null,
    artist: '\u590f\u66fc\u00b7\u85cd\u6ce2\u5b89 (Syaman Rapongan)',
    language_claimed: 'Tao (Yami)',
    language_evidence: 'Artist is a known Tao author and cultural figure from Orchid Island (Lanyu).',
    ethnic_group_claimed: 'Tao (Yami)',
    ethnic_group_evidence: 'Artist is Tao, from Orchid Island. Cultural context documented.',
    performers: [],
    source_platform: 'YouTube',
    url: null,
    youtube_url: null,
    lyrics_url: null,
    album_or_source: 'Cultural documentation recording',
    year: '2012',
    location_claimed: 'Orchid Island (Lanyu)',
    region: 'Taitung',
    genre: 'Traditional',
    tags: ['tao', 'yami', 'traditional', 'orchid-island'],
    source_snippets: '[MOCK DATA \u2014 synthetic entry for UI testing]',
    verification_notes: 'Lyrics exist in documentation but rights status unclear. Do not display publicly until rights are confirmed.',
    confidence: 'medium',
    verification_status: 'candidate',
    needs_manual_verification: true,
    checked_by_me: false,
    date_added: '2026-05-14',
    lyrics: {
      song_id: 'sof-006',
      lyrics_original: '[Tao lyric \u2014 not for public display]',
      lyrics_romanized: null,
      lyrics_translation_zh: null,
      lyrics_translation_en: null,
      lyrics_source: 'Documentation recording',
      lyrics_rights_status: 'unknown',
      lyrics_notes: 'Rights status unclear. Awaiting confirmation from cultural custodian.',
      has_permission: false,
      show_publicly: false
    }
  },
  {
    id: 'sof-007',
    title_original: 'O Misanga No Radiw',
    title_romanized: null,
    title_chinese: '\u6b4c\u8b20\u7684\u7e54\u7dda',
    artist: '\u963f\u7f8e\u65cf\u5a66\u5973\u5408\u5531\u5718 (Amis Women\u2019s Choir)',
    language_claimed: 'Amis',
    language_evidence: 'Choir is explicitly documented as Amis. Title contains Amis words (misanga = to weave, radiw = song/melody).',
    ethnic_group_claimed: 'Amis (Pangcah)',
    ethnic_group_evidence: 'Choir members documented as Amis women from Hualien.',
    performers: [],
    source_platform: 'YouTube',
    url: null,
    youtube_url: null,
    lyrics_url: null,
    album_or_source: 'Council of Indigenous Peoples archive',
    year: '2003',
    location_claimed: 'Hualien',
    region: 'Hualien',
    genre: 'Traditional Choral',
    tags: ['amis', 'traditional', 'choral', 'women', 'archive'],
    source_snippets: '[MOCK DATA \u2014 synthetic entry for UI testing. Romanization not available for this record.]',
    verification_notes: 'Romanization missing \u2014 requires Amis language specialist to confirm spelling. Year estimated from archive metadata.',
    confidence: 'medium',
    verification_status: 'needs_review',
    needs_manual_verification: true,
    checked_by_me: false,
    date_added: '2026-05-14'
  }
];

writeFileSync('data/songs.mock.json', JSON.stringify(data, null, 2), 'utf8');
console.log('Written OK, size:', JSON.stringify(data, null, 2).length, 'bytes');
